# Generated by Django 3.2.7 on 2021-09-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
